### ISSUE TITLE
This resolver is trying to find the wrong plugin

### ISSUE THREAD

**Issue by adrianmcli** [olalonde/eslint-import-resolver-babel-root-import#5]
This resolver currently does not work. This is because the naming convention has changed.

From [line 36](https://github.com/olalonde/eslint-import-resolver-babel-root-import/blob/master/src/index.js#L36):

```js
p[0] === 'babel-root-import'
```

It's trying to find the plugin settings from the `.babelrc` file, but the plugin name is no longer `babel-root-import`. It's now `babel-plugin-root-import`. So if you simply make that change in the string:

```js
p[0] === 'babel-plugin-root-import'
```

This package suddenly works again!

**Comment by adrianmcli** [comment]
@olalonde I have made a PR for this: #6 

Please merge and release if it looks good! I am eager to get this working!!!

**Comment by tzapu** [comment]
any news on sorting this?
cheers

**Comment by antl3x** [comment]
Nothing?

**Comment by olalonde** [comment]
I'm no longer maintaining this but both @cle1994 @GollyJer have commit access
